fixing recepie path

diff --git a/.github/workflows/integration_tests.yaml b/.github/workflows/integration_tests.yaml
--- a/.github/workflows/integration_tests.yaml
+++ b/.github/workflows/integration_tests.yaml
@@ -1,11 +1,21 @@
 on:
+  push:
+    branches:
+      - main
+  pull_request:
   workflow_dispatch:  # Trigger workflow manually from GitHub UI
 
 name: Integration Tests
 
 jobs:
-  ## Integration tests ##
   integration-rattler:
+    # NOTES:
+    #   - `pipefail` must be enabled in order to get the exit code from the conda-recipe-manager commands when
+    #     the output is piped into `tee`
+    #   - We setup empty environment variables like `PREFIX` to suppress rattler-build dry-run failures that are
+    #     specific to the expected build environment. Such a failure does not reflect our ability to convert recipe
+    #     files successfully. We should remove these environment changes if/when rattler-build gives us another way to
+    #     validate recipe files.
     runs-on: ubuntu-latest
     timeout-minutes: 45
     name: Test on ${{ matrix.test-directory }}
@@ -13,20 +23,23 @@ jobs:
       fail-fast: false
       matrix:
         test-directory:
-          - anaconda_recipes_01  # Only one directory for now
+          - anaconda_recipes_01
+        include:
+          - test-directory: anaconda_recipes_01
+            convert-success: 0.90
+            rattler-success: 0.75
     steps:
       - uses: actions/checkout@v4
       - uses: actions/checkout@v4
         with:
           repository: conda-incubator/conda-recipe-manager-test-data
           path: test_data
-          sparse-checkout: recipes_v0/${{ matrix.test-directory }}
-
+          sparse-checkout: |
+            recipes_v0/anaconda_recipes_01
       - uses: ./.github/actions/setup-env
         with:
           python-version: "3.11"
-
-      - name: Convert recipes and full rattler-build
+      - name: Convert recipes and dry-run rattler-build
         run: |
           source $CONDA/bin/activate
           conda activate conda-recipe-manager
@@ -35,16 +48,12 @@ jobs:
           set -o pipefail
           export PREFIX=""
           export RECIPE_DIR=""
-          echo "Loading allow-list from integration_build_test_config.json"
-          ALLOW_LIST=$(cat integration_build_test_config.json | jq -r '.v0_test_files[]')
-          echo "$ALLOW_LIST" > allow_list.txt
-          
-          while read -r recipe; do
-            echo "Processing recipe: $recipe"
-            crm convert "$recipe" --output recipe.yaml | tee -a logs/convert.log
-            rattler-build build recipe.yaml | tee -a logs/build.log || echo "Build failed for $recipe" >> logs/failed_recipes.log
-          done < allow_list.txt
-
+          conda-recipe-manager \
+            convert -t -m ${{ matrix.convert-success }} -o recipe.yaml test_data/recipes_v0/${{ matrix.test-directory }} \
+            | tee logs/convert_${{ matrix.test-directory }}.log
+          conda-recipe-manager \
+            rattler-bulk-build -t -m ${{ matrix.rattler-success }} test_data/recipes_v0/${{ matrix.test-directory }} --render-only \
+            | tee logs/rbb_${{ matrix.test-directory }}.log
       - uses: actions/upload-artifact@v4
         with:
           name: integration-logs-${{ matrix.test-directory }}
@@ -52,9 +61,11 @@ jobs:
 
   integration-final-results:
     runs-on: ubuntu-latest
+    name: Integration Testing Final Report
     needs: [integration-rattler]
+    timeout-minutes: 5
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
       - uses: ./.github/actions/setup-env
         with:
           python-version: "3.11"
